name: Atlas Mine Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yaml
    with:
      filters:
        subgraph:
          - "packages/abis/src/AtlasMine.json"
      subgraph: atlas-mine
    secrets: inherit
