name: Deploy Subgraph

on:
  workflow_call:
    inputs:
      filters:
        description: 'Additional filters to check for changes'
        required: true
        type: string
      subgraph:
        description: 'The name of the subgraph to check for changes'
        required: true
        type: string

jobs:
  changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      general: ${{ steps.general.outputs.subgraph }}
      specific: ${{ steps.specific.outputs.subgraph }}
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Detect general changes
      uses: dorny/paths-filter@v2
      id: general
      with:
        filters: |
          subgraph:
            - ".github/workflows/deploy.yaml"
            - "package.json"
            - "yarn.lock"
            - ".github/workflows/${{ inputs.subgraph }}.yaml"
            - "subgraphs/${{ inputs.subgraph }}/**"

    - name: Detect specific changes
      uses: dorny/paths-filter@v2
      id: specific
      with:
        filters: ${{ inputs.filters }}

  deploy:
    name: Deploy
    if: ${{ needs.changes.outputs.general == 'true' || needs.changes.outputs.specific == 'true' }}
    needs: changes
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./subgraphs/${{ inputs.subgraph }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Download deps
        uses: bahmutov/npm-install@v1

      - name: Setup environment
        uses: Firenza/secrets-to-env@v1.2.0
        with:
            secrets: ${{ toJSON(secrets) }}

      - name: Prepare
        run: yarn prepare

      - name: Generate
        run: yarn codegen

      - name: Authenticate
        run: yarn graph auth --product hosted-service ${{ secrets.GRAPH_TOKEN }}

      - name: Deploy
        run: yarn graph deploy --product hosted-service wyze/${{ inputs.subgraph }}

      - name: Fallback Deploy
        if: ${{ failure() }}
        run: yarn deploy
