name: Floor Prices Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yaml
    with:
      filters: .github/floor-prices-filters.yaml
      subgraph: floor-prices
    secrets: inherit
