name: MAGIC Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yaml
    with:
      filters: .github/erc20-filters.yaml
      subgraph: magic
    secrets: inherit
