name: Smol Domains Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yaml
    with:
      filters: |
        subgraph:
          - "packages/abis/src/SmolDomains.json"
      subgraph: smol-domains
    secrets: inherit
