name: Treasures Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yaml
    with:
      filters: .github/erc1155-filters.yaml
      subgraph: treasures
    secrets: inherit
